import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; // Import this to allow fast page switching
import Navbar from "@/app/ui/navbar";
import "@/app/ui/globals.css";
import { inter } from "./ui/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-white`}
      >
        <Navbar />
        {/* The actual page content */}
        <main className="min-h-screen">{children}</main>

        {/* Simple Footer */}
        <footer className="p-8 border-t border-slate-800 text-center text-slate-500 text-sm">
          © 2025 Prepared for Cousin's Tech Co.
        </footer>
      </body>
    </html>
  );
}
